entity_reference_widget_helpers.settings:
  type: config_object
  label: 'Entity reference widget helpers settings'
  mapping:
    ief_choose_wording:
      type: string
      label: 'Wording to use for IEF "Add existing" button'
